environment:
    global:
          PYTHON: "C:\\conda"
          MINICONDA_FILENAME: "Miniconda3-latest-Windows-x86_64.exe"
    matrix:
          - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
            PYTHON_VERSION: "3.6"

platform:
    - x64

install:
    - "powershell appveyor\\download_and_install_miniconda.ps1"
    - "powershell appveyor\\configure_conda_and_install_pfnet.ps1"

build: false

test_script:
    - "conda activate testenv"
    - "conda env list"
    - "python setup.py build_ext --inplace"
    - "nosetests -s -v"