environment:
  matrix:
  - TOXENV: py36
  
platform:
    - x64

install:
    - "pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy"
    - "pip install -r requirements.txt"

build: off

before_build:
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
    - echo %PATH%
    - "%CMD_IN_ENV% python setup.py build_ext --inplace"

test_script:
    - "%CMD_IN_ENV% nosetests -s -v"