environment:
    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"

    matrix:
        - PYTHON_VERSION: "3.6"

platform:
    - x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "pip install toolz"
    - "pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy"
    - "pip install -r requirements.txt"

build: false

before_build:
    - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
    - echo %PATH%
    - "%CMD_IN_ENV% python setup.py build_ext --inplace"

test_script:
    - "%CMD_IN_ENV% nosetests -s -v"